AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  awdatenspendeapi:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: .
      Description: ''
      MemorySize: 6000
      Timeout: 900
      Role: >-
        arn:aws:iam::519969025508:role/service-role/aw-datenspende-api-role-yigqfy51
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
        Api1:
          Type: Api
          Properties:
            Path: /aw-datenspende-api
            Method: ANY
