AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  awdatenspendepull:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: ''
      MemorySize: 512
      Timeout: 600
      Role: >-
        arn:aws:iam::519969025508:role/service-role/aw-datenspende-api-role-yigqfy51
